### PR TITLE
fix loading of parent handles in TPM TSS2 keys

### LINKED ISSUE #152: Loading of TPM2-TSS keys created with version earlier than 1.2.0 always fails
**Highlevel problem description**
I discovered a problem, that TPM2-TSS keys which have been created with the tpm2-openssl provider with a version lower than 1.2.0 or with the tpm2-tss-engine with a version lower than 1.2.0-rc0 can no longer be loaded with the current provider implementation.

**Code that triggers the problem**
```
/* Set TPM-based key */
    OSSL_PROVIDER *prov_tpm2 = NULL;
    OSSL_PROVIDER *prov_default = NULL;
    OSSL_STORE_CTX *ctx = NULL;
    OSSL_STORE_INFO *info = NULL;
    EVP_PKEY *pKey = NULL;
    UI_METHOD *ui_method = NULL;

    /* Load default provider */
    if ((prov_default = OSSL_PROVIDER_load(NULL, "default")) == NULL) {
      perror("Unable to load OpenSSL provider: default.");
      exit(EXIT_FAILURE);
    }

    /* Self-test */
    if (!OSSL_PROVIDER_self_test(prov_default)) {
      perror("OpenSSL provider (default) self test failed.");
      exit(EXIT_FAILURE);
    }

    /* Load TPM2 provider */
    if ((prov_tpm2 = OSSL_PROVIDER_load(NULL, "tpm2")) == NULL) {
      perror("Unable to load OpenSSL provider: tpm2.");
      exit(EXIT_FAILURE);
    }

    /* Self-test */
    if (!OSSL_PROVIDER_self_test(prov_tpm2)) {
      perror("OpenSSL provider (tpm2) self test failed.");
      exit(EXIT_FAILURE);
    }

    if (!(ui_method = UI_UTIL_wrap_read_pem_callback(provide_password, 0))) {
      perror("setting ui_method failed");
      exit(EXIT_FAILURE);
    }
    const char *password = "mysupersecretpassword";

    if ((ctx = OSSL_STORE_open_ex("mytpm2tsskey.pem", NULL, "?provider=tpm2", ui_method,
                                  (void *)password, NULL, NULL, NULL)) ==
            NULL ||
        !OSSL_STORE_expect(ctx, OSSL_STORE_INFO_PKEY) ||
        (info = OSSL_STORE_load(ctx)) == NULL ||
        (pKey = OSSL_STORE_INFO_get1_PKEY(info)) == NULL) {
      perror("OpenSSL provider (tpm2) key loading failed.");
      exit(EXIT_FAILURE);
    }

    OSSL_STORE_close(ctx);
```
I'm always getting:
> OpenSSL provider (tpm2) key loading failed.

Because OSSL_STORE_load(ctx) returns NULL.

**Analysis**
The problem actually arises when reading the parent key handle from the ASN1 structure
https://github.com/tpm2-software/tpm2-openssl/blob/8a5572639742dee5bc0b370ac04547b4b8ab2e0f/src/tpm2-provider-pkey.c#L138

The error has been introduced when fixing https://github.com/tpm2-software/tpm2-openssl/issues/74.

Prior to the fix, the parent handle has been saved using ASN1_INTEGER_set().
https://github.com/tpm2-software/tpm2-openssl/blob/611facfd5e7a19c2c2404c69d9e190c9f594c6e2/src/tpm2-provider-pkey.c#L79

keydata->parent is of type TPM2_HANDLE, which is an uint32_t
https://github.com/tpm2-software/tpm2-tss/blob/bd67f321440cabfe1a8b7bbef416e4d4d0c54655/include/tss2/tss2_tpm2_types.h#L1049
ASN1_INTEGER_set() treats the parameter as (signed!) long: https://docs.openssl.org/3.6/man3/ASN1_INTEGER_get_int64. This resulted in the problems described in https://github.com/tpm2-software/tpm2-openssl/issues/74: On a 32-bit system the MSB was set and therefore the value was considered to be negative.

This problem was fixed by calling ASN1_INTEGER_set_uint64 and ASN1_INTEGER_get_uint64: https://github.com/tpm2-software/tpm2-openssl/commit/ff40b6f9be5f6487a1fde7a2afdd6f399d7f1368
This works perfectly well when writing and reading new keys. When a key generated using the previous implementation should be loaded, it fails, due to the set bit V_ASN1_NEG in the type
https://github.com/openssl/openssl/blob/134f17d526a5d0a9fbd66adf85e53df8a764a2ff/crypto/asn1/a_int.c#L388

The initial problem was also discovered in the  tpm2-tss-engine and has been fixed in version 1.2.0-rc0
https://github.com/tpm2-software/tpm2-tss-engine/pull/222
If you read through the threads you'll see that @AndreasFuchsTPM was making sure backwards compatibility was given.

Additionally the problem has also been addressed in the tpm2-tools:
https://github.com/tpm2-software/tpm2-tools/pull/3113/commits/5e685448de7769a0f2b45c91cd70e9ef256bacc6

**Fix**
I created a MR with a potential fix. I don't have the environment to test all possible cases and it would definitely be helpful to have tests which cover all the cases. This seems to have been done for the engine. I see this task in the hands of the maintainers.

I decided to go with the same principle used by the engine and the tpm2-tools by using BIGNUM for serialization and deserialization - for the sake of harmonization and maintainability (do the same thing the same way in all of the projects).
It would also be possible to solve the issue by keeping the serialization using uint64. This would result in a manual check in the provider is V_ASN1_NEG is set. And then conditionally call ASN1_INTEGER_get_uint64 or ASN1_INTEGER_get.

### PR DESCRIPTION
**Pull request by gotthardp**
Fixes: #152

### CODE REVIEW

**Comment by gotthardp** [comment]
This supersedes the #153.

File: src/tpm2-provider-pkey.c [hunk 1]
```diff
@@ -135,9 +144,14 @@ tpm2_keydata_read(BIO *bin, TPM2_KEYDATA *keydata, TPM2_PKEY_FORMAT format)
...
         goto error;
 
+    if (BN_is_negative(bn_parent))
+        parent = ASN1_INTEGER_get(tpk->parent);
+    else
+        parent = BN_get_word(bn_parent);
+
     if (parent == 0)
         keydata->parent = TPM2_RH_OWNER;
     else if (parent <= UINT32_MAX)
```
Comment (thomkopp) [inline src/tpm2-provider-pkey.c:157]: By changing parent from type uint64_t to TPM2_HANDLE (which according to tpm2-tss is an uint32_t see: https://github.com/tpm2-software/tpm2-tss/blob/a54a27df0732cde2c47b1d4d0e7bef489dc8a7d5/include/tss2/tss2_tpm2_types.h#L1050 and https://github.com/tpm2-software/tpm2-tss/blob/a54a27df0732cde2c47b1d4d0e7bef489dc8a7d5/include/tss2/tss2_common.h#L24) this line will always be true.

Have a look at line 153:
BN_get_word returns an BN_ULONG, which is 32-bits on 32-bit systems and 64-bits on 64-bit systems.
BN_get_word set's all bits in case of an error.

parent is of type TPM2_HANDLE which is of type uint32_t.

On a 64 bit system, we're performing an implicit conversion from uint64 to uint32. This shouldn't be a problem in case of a valid parent-handle as they're in the range 0x81000000 - 0x81FFFFFF. I think we should handle the case where BN_get_word() returns something bigger than a 32bit value on 64bits systems and on 32bit systems we should treat the return value UINT32_MAX as error.

**Comment by thomkopp** [comment]
I would have loved to see a comment in the final code, regarding the reason for this change. This is due to compatiblity with older provider/engine versions.

I took quite an effort to analyze and document everything here:
https://github.com/tpm2-software/tpm2-openssl/pull/153/changes/30d57cf533d232481db265899980c676488bb916#diff-b7d2c2757e9c2e3ca8b0f9c475fa9921fc8b4f569a2cacdc43393fbf37c470dbR148

That might be helpful in the future.
